### ISSUE TITLE
イメージのビルドと Docker Hub へのプッシュ

### ISSUE THREAD

**Issue by kamataryo** [geolonia/geolonia-locations-action#3]

**Comment by keichan34** [comment]
@kamataryo Docker Hub にプッシュするとどうなります？（docsさくっと見てるんですがpublishしなくてもアクションとしては使えそう、、。ですよね？）Github Actions以外でも使えるようにするということですかね？

**Comment by kamataryo** [comment]
@keichan34 はい、このままでも使えます。
Docker Hub から参照した方がイメージをビルドする時間が速いかと思いました。まだ試してないのですが..
今1分くらいかかってます。
