### ISSUE TITLE
ポイントが1つの時に、tippecanoe の -zg オプションが失敗する

### ISSUE THREAD

**Issue by naogify** [geolonia/geolonia-locations-action#6]
ポイントが1つの時に、tippecanoe の -zg オプションが失敗する。
https://github.com/naogify/vector-tiles-api/actions/runs/3224420861/jobs/5275527105

![スクリーンショット 2022-10-11 14 52 39](https://user-images.githubusercontent.com/8760841/195007652-b6072d64-03ab-45fc-84d3-695fd5170611.png)

**Comment by keichan34** [comment]
この場合は maxzoom 8 とかにしましょうか
