### ISSUE TITLE
データの maxzoom をデフォルトで 22 に指定したい

### ISSUE THREAD

**Issue by naogify** [geolonia/geolonia-locations-action#7]
https://raw.githubusercontent.com/naogify/vector-tiles-api/gh-pages/example.geojson をタイルに変換した所、

タイルのMaxzoom が8に設定された。（Tippecanoeの設定？）
https://github.com/naogify/vector-tiles-api/blob/gh-pages/tiles/metadata.json#L6

なので、タイル側で maxzoom を指定してオーバーズームにしないと、地物が表示されない。

```
  map.addSource("my-data", {
    type: "vector",
    tiles: ["https://naogify.github.io/vector-tiles-api/tiles/{z}/{x}/{y}.mvt"],
    maxzoom: 8
  });
```

デフォルトのmaxzoom を mapbox に合わせて 22 に指定したい。
https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#vector-maxzoom

**Comment by keichan34** [comment]
z22に設定すると、z22までタイルを生成してかなり時間と容量が使うので、この場合はmaxzoom 8 が適切だと思います（z=8のデータをオーバズームを使ってそれ以降の地図に表示する）

**Comment by naogify** [comment]
@keichan34 

サンプルを作る時に、データ側で maxzoom 8 が指定されていることに気づかずかなりハマったんですよね、、。
ユーザーさんがデータの maxzoom の確認をしなくても、地物を表示できるようにしたいなと思いました。

これって例えば、`metadata.json` を使って、Javascript 側で オーバーズームを指定しなくても表示されるようにできたりしないでしょうか？（`tiles.json`のように？）

**Comment by keichan34** [comment]
tiles.jsonを作ってあげるといいですね
